float64 altitude                      # altitude at which the coverage takes place
---
string target_id                      # id of the found target
geometry_msgs/PoseStamped target_pose # position of the found target
---
