std_msgs/Header header          # ros header
swarmros/EventHeader swarmio    # cpswarm swarmio swarmros header
std_msgs/Float64 cart_0_theta   # orientation of the cart 0
std_msgs/Float64 cart_0_x       # x of the cart 0
std_msgs/Float64 cart_0_y       # y of the cart 0
std_msgs/Float64 cart_1_theta   # orientation of the cart 1
std_msgs/Float64 cart_1_x       # x of the cart 1
std_msgs/Float64 cart_1_y       # y of the cart 1
std_msgs/Float64 cart_2_theta   # orientation of the cart 2
std_msgs/Float64 cart_2_x       # x of the cart 2
std_msgs/Float64 cart_2_y       # y of the cart 2
std_msgs/Float64 cart_3_theta   # orientation of the cart 3
std_msgs/Float64 cart_3_x       # x of the cart 3
std_msgs/Float64 cart_3_y       # y of the cart 3
std_msgs/Float64 cart_4_theta   # orientation of the cart 4
std_msgs/Float64 cart_4_x       # x of the cart 4
std_msgs/Float64 cart_4_y       # y of the cart 4
std_msgs/Float64 cart_5_theta   # orientation of the cart 5
std_msgs/Float64 cart_5_x       # x of the cart 5
std_msgs/Float64 cart_5_y       # y of the cart 5
std_msgs/Float64 cart_6_theta   # orientation of the cart 6
std_msgs/Float64 cart_6_x       # x of the cart 6
std_msgs/Float64 cart_6_y       # y of the cart 6
std_msgs/Float64 cart_7_theta   # orientation of the cart 7
std_msgs/Float64 cart_7_x       # x of the cart 7
std_msgs/Float64 cart_7_y       # y of the cart 7
std_msgs/Float64 cart_8_theta   # orientation of the cart 8
std_msgs/Float64 cart_8_x       # x of the cart 8
std_msgs/Float64 cart_8_y       # y of the cart 8
std_msgs/Float64 cart_9_theta   # orientation of the cart 9
std_msgs/Float64 cart_9_x       # x of the cart 9
std_msgs/Float64 cart_9_y       # y of the cart 9



