geometry_msgs/Point position # The current position to compare the waypoint against.
float64 tolerance            # The distance to the current waypoint below which the next waypoint of the path is selected.
---
geometry_msgs/Point point    # The waypoint to navigate to.
bool valid                   # Whether the waypoint is valid.
